[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    Basic-Auth = "admin:secret123"

# 開発環境用の環境変数
[context.deploy-preview]
  environment = { NODE_ENV = "staging" }

# 本番環境用の環境変数
[context.production]
  environment = { NODE_ENV = "production" }
