[build]
  publish = "."

# ベーシック認証の設定
[context.production]
  environment = { NODE_ENV = "production" }
  [context.production.environment]
    BASIC_AUTH_USER = "admin"
    BASIC_AUTH_PASS = "secret123"

# 開発環境用の環境変数
[context.deploy-preview]
  environment = { NODE_ENV = "staging" }
  [context.deploy-preview.environment]
    BASIC_AUTH_USER = "admin"
    BASIC_AUTH_PASS = "secret123"
